version: '2'
services:
  server:
    build: .
    volumes:
      - /exports:/exports
      - /lib/modules:/lib/modules:ro
    ports:
      - '2049:2049'
      - '111:111/udp'
    privileged: true
    cap_add:
      - ALL
    environment:
      - EXPORTS=/exports *(rw,async,no_root_squash,no_subtree_check)
      - RPC_BIND_OPTS="-f -d"
      - NFS_RPC_NFSD_COUNT=8
      - NFS_RPC_MOUNT_OPTS=--manage-gids -F --debug all
      - NFS_RPC_NFSD_OPTS=--debug
